// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id            int         `json:"Id"            description:"userid"`                            // userid
	Email         string      `json:"Email"         description:"邮箱"`                                // 邮箱
	Mobile        string      `json:"Mobile"        description:"手机号"`                               // 手机号
	Name          string      `json:"Name"          description:"姓名"`                                // 姓名
	Password      string      `json:"Password"      description:"密码"`                                // 密码
	DepartmentIds string      `json:"DepartmentIds" description:"部门id,一个人可能属于多个部门"`                  // 部门id,一个人可能属于多个部门
	UpdateTime    *gtime.Time `json:"UpdateTime"    description:"更新时间"`                              // 更新时间
	LastLoginTime *gtime.Time `json:"LastLoginTime" description:"最近一次登录时间, 后期可以清理离职用户, 否则这张表只增加不减少"` // 最近一次登录时间, 后期可以清理离职用户, 否则这张表只增加不减少
	Roles         string      `json:"Roles"         description:"用户角色信息,数组形式"`                       // 用户角色信息,数组形式
}
